### ISSUE TITLE
ember install command adds old version of addon

### ISSUE THREAD

**Issue by GauravShetty1016** [ember-mobile/ember-cli-framework7#17]
I am unable to install the latest version of the code using ember install. I only get the older version according to the data in package.json

**Comment by jamesdixon** [comment]
@spieker would you be able to do a quick npm publish of the latest? Thx!

**Comment by spieker** [comment]
@jamesdixon can't you just reference the git commit for now?

```
{
  "ember-cli-framework7": "ember-mobile/ember-cli-framework7#6180d7d"
}
```

I'm working on a re-write at the moment (see `develop`branch), as soon as I find time to finish it, I'll make a new release to NPM.

**Comment by jamesdixon** [comment]
I am, just thought it would be helpful for others. Didn’t realize you were working on a re-write!

**Comment by GauravShetty1016** [comment]
This is no longer necessary. +1 for a better addon!
