### ISSUE TITLE
Example using Framework7 router?

### ISSUE THREAD

**Issue by jcope2013** [ember-mobile/ember-cli-framework7#2]
hey thanks for the work so far on this, have you had the chance to mess around any trying to build on top of the Framework7 router (http://www.idangero.us/framework7/docs/router-api.html) using the ember router so you get the Framework7 animations when transitioning between routes?

**Comment by spieker** [comment]
No, I have used liquid-fire (https://github.com/ef4/liquid-fire) for animations. Also I don't think it's possible.
