### ISSUE TITLE
UI not visible in test container

### ISSUE THREAD

**Issue by engwan** [ember-mobile/ember-cli-framework7#21]
Instead of:

```
body > .ember-view {
  height: 100%;
}
```

I think this is better:

```
.ember-application > .ember-view {
    height: 100%;
}
```

Because there are extra divs during testing. And it will also make it work for ember applications embedded within a page.

**Comment by spieker** [comment]
Thanks, for the info. Could you create a PR with this change? I'll merge it then asap.
