### ISSUE TITLE
Addon doesn't work with latest ember-cli

### ISSUE THREAD

**Issue by gillp** [ember-mobile/ember-cli-framework7#7]
Ember-cli version 2.7

Create a new project, install the add on per instructions, port over the dummy app. 

Panel swipe doesn't work, sort doesn't work, search bar is missing

**Comment by hoboman313** [comment]
You were not using 2.7...2.7 is in beta now.

Judging by the fact that the addon maintainer still hasn't replied and the fact that the addon's package.json references ember-cli 0.1.4 ( ~1.5 years old now ), I would discourage anyone from trying to use this.

**Comment by GavinJoyce** [comment]
@spieker can this be closed or does this addon only target earlier versions of ember cli?

**Comment by spieker** [comment]
@GavinJoyce I haven't worked on the master branch so no, it's not working. But I've started a re-write of the addon some time ago on the `develop` branch. It's missing the components for now and I wouldn't have time to add them in the next days but if a service to initialize `F7` is enough for you, feel free to start using it.

**Comment by GavinJoyce** [comment]
Thanks @spieker, I'll work from the `develop` branch
